import "@/styles/globals.css";
import { Inter, Poppins } from "next/font/google";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const font = Poppins({ subsets: ["latin"], weight: ["100", "200"] });

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
