import "@/styles/globals.css";
import { Nunito_Sans } from "next/font/google";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const font = Nunito_Sans({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
