import "@/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { ruRU } from "@clerk/localizations";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider localization={ruRU}>
            <html lang="en">
                <body className={`${inter.className}`}>{children}</body>
            </html>
        </ClerkProvider>
    );
}
