import "@/styles/globals.css";
import { Nunito_Sans } from "next/font/google";

const font = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
    title: "Tripma",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${font.className}`}>{children}</body>
        </html>
    );
}
